version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: another-me-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./ame:/app/ame
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - VECTOR_DB_PATH=/app/data/vector_store
      - UPLOAD_DIR=/app/data/uploads
      - DATA_DIR=/app/data
    restart: unless-stopped
    networks:
      - another-me-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: another-me-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - another-me-network

networks:
  another-me-network:
    driver: bridge

volumes:
  data:
