version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/docker/Dockerfile.backend
    container_name: another-me-backend
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
    restart: unless-stopped
    networks:
      - another-me-network

  frontend:
    build:
      context: ..
      dockerfile: deployment/docker/Dockerfile.frontend
    container_name: another-me-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - another-me-network

networks:
  another-me-network:
    driver: bridge

volumes:
  data:
